default: &default
  adapter: postgresql
  enconding: unicode
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  pool: 5

development:
  <<: *default
  database: gen_provas_development

test:
  <<: *default
  database: gen_provas_test
